# Generated by Django 6.0.2 on 2026-02-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
