# Generated by Django 6.0.2 on 2026-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact_info', models.TextField()),
                ('medical_history', models.TextField(blank=True)),
            ],
        ),
    ]
